2024-09-18 14:34:16,225 - app - INFO - At index page
2024-09-23 01:22:34,738 - app - INFO - decide_respond ::: Responding with choice of True
2024-09-23 01:24:30,678 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 01:28:07,978 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 01:53:08,883 - app - DEBUG - decide_respond:::Comment is a reply to another comment
2024-09-23 01:58:27,243 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 01:58:29,860 - app - DEBUG - decide_respond ::: Responding with choice of False
2024-09-23 01:58:48,150 - app - DEBUG - decide_respond:::Comment is a reply to another comment
2024-09-23 01:58:48,152 - app - DEBUG - decide_respond:::Cannot reply to comment for which this reporter is not in the chain of
2024-09-23 02:13:07,923 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:13:09,347 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:13:09,481 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:13:10,844 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:13:19,228 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:13:31,621 - app - DEBUG - decide_respond ::: Responding with choice of False
2024-09-23 02:14:12,784 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:14:14,223 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:14:42,580 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:14:49,792 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:14:49,916 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:14:51,267 - app - DEBUG - decide_respond ::: Responding with choice of False
2024-09-23 02:15:36,462 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:15:40,699 - app - DEBUG - decide_respond ::: Responding with choice of False
2024-09-23 02:15:40,829 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:15:43,347 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:15:43,479 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:15:44,879 - app - DEBUG - decide_respond ::: Responding with choice of False
2024-09-23 02:15:45,003 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:15:46,369 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:15:46,496 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:15:48,775 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:17:18,393 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:17:28,708 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:18:10,709 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:18:12,161 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:18:13,147 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:18:14,601 - app - DEBUG - decide_respond ::: Responding with choice of False
2024-09-23 02:18:17,196 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:18:18,598 - app - DEBUG - decide_respond ::: Responding with choice of False
2024-09-23 02:19:33,468 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:19:35,877 - app - DEBUG - decide_respond ::: Responding with choice of False
2024-09-23 02:22:27,420 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:22:33,281 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:22:41,105 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:22:42,465 - app - DEBUG - decide_respond ::: Responding with choice of True
2024-09-23 02:23:11,959 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:23:13,344 - app - DEBUG - decide_respond ::: Responding with choice of False
2024-09-23 02:23:13,465 - app - DEBUG - decide_respond:::Comment is a top level comment
2024-09-23 02:23:14,852 - app - DEBUG - decide_respond ::: Responding with choice of False
2025-01-10 14:49:50,381 - app - ERROR - Exception on /reporters [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 150, in reporters
    return render_template("reporters.html", reporters=reporters)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/reporters.html", line 13, in top-level template code
    <h1 class="text-3xl text-white"><a href="{{url_for('index')}}">UPDOG's Reporters</a></h1>
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2025-01-10 14:49:59,448 - app - ERROR - Exception on /about [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 154, in about
    return render_template("about.html")
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/about.html", line 14, in top-level template code
    <h1><a href="{{ url_for('index') }}">What UP-Bout Us?</a></h1>
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2025-01-10 15:21:10,606 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/sql/base.py", line 2181, in _entity_namespace_key
    return getattr(ns, key)  # type: ignore
AttributeError: type object 'User' has no attribute 'email'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 53, in login
    user = User.query.filter_by(email=form.email.data).first()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 1983, in filter_by
    clauses = [
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 1984, in <listcomp>
    _entity_namespace_key(from_entity, key) == value
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/sql/base.py", line 2183, in _entity_namespace_key
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Entity namespace for "user" has no property "email"
2025-01-10 15:24:25,799 - app - ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 60, in login
    return render_template('login.html', title='Login', form=form)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/grant/Workspace/updog-news/app/templates/base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
  File "/home/grant/Workspace/updog-news/app/templates/login.html", line 18, in block 'content'
    <div>{{ form.username.label }} {{ username.email }}</div>
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.forms.LoginForm object' has no attribute 'username'
2025-01-10 15:24:26,991 - app - ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 60, in login
    return render_template('login.html', title='Login', form=form)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/grant/Workspace/updog-news/app/templates/base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
  File "/home/grant/Workspace/updog-news/app/templates/login.html", line 18, in block 'content'
    <div>{{ form.username.label }} {{ username.email }}</div>
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.forms.LoginForm object' has no attribute 'username'
2025-01-10 15:27:55,976 - app - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 45, in register
    db.session.commit()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: user.username
[SQL: INSERT INTO user (username, password) VALUES (?, ?)]
[parameters: (None, '$2b$12$ASBzmLL.y20Kg8AgVX18a..p/fqYk4DcZ3I2km9cX5jI0/iunxFoO')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-01-10 15:30:13,647 - app - ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 62, in login
    return render_template('login.html', title='Login', form=form)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/grant/Workspace/updog-news/app/templates/base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
  File "/home/grant/Workspace/updog-news/app/templates/login.html", line 18, in block 'content'
    <div>{{ form.username.label }} {{ username.email }}</div>
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'username' is undefined
2025-01-10 15:31:21,041 - app - ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 60, in login
    return render_template('login.html', title='Login', form=form)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/grant/Workspace/updog-news/app/templates/base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
  File "/home/grant/Workspace/updog-news/app/templates/login.html", line 18, in block 'content'
    <div>{{ form.username.label }} {{ username.email }}</div>
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'username' is undefined
2025-01-10 15:33:04,836 - app - ERROR - Exception on /reporters [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 150, in reporters
    return render_template("reporters.html", reporters=reporters)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/reporters.html", line 13, in top-level template code
    <h1 class="text-3xl text-white"><a href="{{url_for('index')}}">UPDOG's Reporters</a></h1>
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2025-01-10 15:33:46,481 - app - ERROR - Exception on /reporters [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 150, in reporters
    return render_template("reporters.html", reporters=reporters)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/reporters.html", line 13, in top-level template code
    <h1 class="text-3xl text-white"><a href="{{url_for('index')}}">UPDOG's Reporters</a></h1>
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2025-01-10 15:34:25,095 - app - ERROR - Exception on /reporters [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 150, in reporters
    return render_template("reporters.html", reporters=reporters)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/reporters.html", line 13, in top-level template code
    <h1 class="text-3xl text-white"><a href="{{url_for('index')}}">UPDOG's Reporters</a></h1>
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2025-01-10 15:36:03,698 - app - ERROR - Exception on /reporters [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 150, in reporters
    return render_template("reporters.html", reporters=reporters)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/reporters.html", line 37, in top-level template code
    <li><a href="{{ url_for('about') }}">About</a></li>
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'about'. Did you mean 'main.about' instead?
2025-01-10 15:42:01,983 - app - ERROR - Exception on /reporters [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 150, in reporters
    return render_template("reporters.html", reporters=reporters)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/reporters.html", line 19, in top-level template code
    <a href="{{url_for('reporter', uuid=reporter.uuid, name=reporter.name)}}">
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reporter' with values ['name', 'uuid']. Did you mean 'main.reporter' instead?
2025-01-10 15:42:54,486 - app - ERROR - Exception on /reporters [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 150, in reporters
    return render_template("reporters.html", reporters=reporters)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/reporters.html", line 19, in top-level template code
    <a href="{{url_for('reporter', uuid=reporter.uuid, name=reporter.name)}}">
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reporter' with values ['name', 'uuid']. Did you mean 'main.reporter' instead?
2025-01-10 15:43:29,503 - app - ERROR - Exception on /reporters [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 150, in reporters
    return render_template("reporters.html", reporters=reporters)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/reporters.html", line 19, in top-level template code
    <a href="{{url_for('main.reporter', uuid=reporter.uuid, name=reporter.name)}}">
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reporter' with values ['name', 'uuid']. Did you mean 'main.reporter' instead?
2025-01-10 15:43:46,067 - app - ERROR - Exception on /reporter/e6a5063a-dd60-4b60-86d6-c369ea32918e/Dan [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 388, in reporter
    if results.onetime:
AttributeError: 'Reporter' object has no attribute 'onetime'
2025-01-10 15:44:57,115 - app - ERROR - Exception on /reporter/e6a5063a-dd60-4b60-86d6-c369ea32918e/Dan [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 388, in reporter
    # if results.onetime:
AttributeError: 'Reporter' object has no attribute 'onetime'
2025-01-10 15:48:21,513 - app - ERROR - Exception on /generate [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 277, in connect
    sock = self.retry.call_with_retry(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 278, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 639, in _connect
    raise err
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 627, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 91, in generate
    queue_story(uuid)
  File "/home/grant/Workspace/updog-news/app/queue.py", line 37, in queue_story
    return _manager.queue_story(uuid)
  File "/home/grant/Workspace/updog-news/app/queue.py", line 20, in queue_story
    generate.queue(uuid)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_rq2/functions.py", line 127, in queue
    return self.rq.get_queue(queue_name).enqueue_call(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 719, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 1094, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 1114, in _enqueue_job
    job.redis_server_version = self.get_redis_server_version()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 208, in get_redis_server_version
    self.redis_server_version = get_version(self.connection)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/utils.py", line 293, in get_version
    tuple(int(i) for i in str(connection.info("server")["redis_version"]).split('.')[:3]),
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/commands/core.py", line 996, in info
    return self.execute_command("INFO", section, *args, **kwargs)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 1074, in get_connection
    connection.connect()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
2025-01-10 15:53:15,304 - app - ERROR - Exception on /generate [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 95, in generate
    return render_template("generate_2.html", form=form)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/grant/Workspace/updog-news/app/templates/generate_2.html", line 118, in top-level template code
    fetch(`{{url_for('get_reporters')}}`).then(response => response.json()).then
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'get_reporters'. Did you mean 'main.new_reporter' instead?
2025-01-10 16:07:05,417 - app - ERROR - Exception on /generate [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: sub-select returns 9 columns - expected 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 93, in generate
    db.session.commit()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1227, in _emit_insert_statements
    result = connection.execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) sub-select returns 9 columns - expected 1
[SQL: INSERT INTO queued_story (uuid, title, guideline, user_id, reporter_id) VALUES (?, ?, ?, ?, (SELECT reporter.id, reporter.created, reporter.uuid, reporter.name, reporter.username, reporter.personality, reporter.trashed, reporter.archived, reporter.likes 
FROM reporter 
WHERE reporter.name = ?))]
[parameters: ('6df956a7-c81b-4bd5-976c-b8eb5cbf5ab7', 'huh', 'wut', 1, 'Dan')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-10 16:08:45,318 - app - ERROR - Exception on /generate [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 4 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 93, in generate
    db.session.commit()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 4 - probably unsupported type.
[SQL: INSERT INTO queued_story (uuid, title, guideline, user_id, reporter_id) VALUES (?, ?, ?, ?, ?)]
[parameters: ('7647c3b4-748d-4851-8b90-1917f0f8e8ae', 'huh', 'wut', 1, <Reporter 1>)]
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2025-01-10 16:09:33,473 - app - ERROR - Exception on /generate [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 277, in connect
    sock = self.retry.call_with_retry(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 278, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 639, in _connect
    raise err
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 627, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 95, in generate
    queue_story(uuid)
  File "/home/grant/Workspace/updog-news/app/queue.py", line 37, in queue_story
    return _manager.queue_story(uuid)
  File "/home/grant/Workspace/updog-news/app/queue.py", line 20, in queue_story
    generate.queue(uuid)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_rq2/functions.py", line 127, in queue
    return self.rq.get_queue(queue_name).enqueue_call(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 719, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 1094, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 1114, in _enqueue_job
    job.redis_server_version = self.get_redis_server_version()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 208, in get_redis_server_version
    self.redis_server_version = get_version(self.connection)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/utils.py", line 293, in get_version
    tuple(int(i) for i in str(connection.info("server")["redis_version"]).split('.')[:3]),
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/commands/core.py", line 996, in info
    return self.execute_command("INFO", section, *args, **kwargs)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 1074, in get_connection
    connection.connect()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
2025-01-10 23:24:39,922 - app - ERROR - Exception on /generate [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 89, in generate
    reporter_id = Reporter.query.filter_by(name=form.reporters.data).first().id
AttributeError: 'NoneType' object has no attribute 'id'
2025-01-10 23:26:16,393 - app - ERROR - Exception on /generate [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 277, in connect
    sock = self.retry.call_with_retry(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 278, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 639, in _connect
    raise err
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 627, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 95, in generate
    queue_story(uuid)
  File "/home/grant/Workspace/updog-news/app/queue.py", line 37, in queue_story
    return _manager.queue_story(uuid)
  File "/home/grant/Workspace/updog-news/app/queue.py", line 20, in queue_story
    generate.queue(uuid)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_rq2/functions.py", line 127, in queue
    return self.rq.get_queue(queue_name).enqueue_call(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 719, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 1094, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 1114, in _enqueue_job
    job.redis_server_version = self.get_redis_server_version()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 208, in get_redis_server_version
    self.redis_server_version = get_version(self.connection)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/utils.py", line 293, in get_version
    tuple(int(i) for i in str(connection.info("server")["redis_version"]).split('.')[:3]),
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/commands/core.py", line 996, in info
    return self.execute_command("INFO", section, *args, **kwargs)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 1074, in get_connection
    connection.connect()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
2025-01-10 23:28:34,005 - app - ERROR - Exception on /generate [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 94, in generate
    queuedStory = QueuedStory(uuid=uuid, title=form.title.data, guideline=form.guideline.data, user_id=current_user.id, reporter_id=reporter_id)
NameError: name 'reporter_id' is not defined
2025-01-10 23:31:46,209 - app - ERROR - Exception on /generate [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 277, in connect
    sock = self.retry.call_with_retry(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 278, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 639, in _connect
    raise err
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 627, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 97, in generate
    queue_story(uuid)
  File "/home/grant/Workspace/updog-news/app/queue.py", line 37, in queue_story
    return _manager.queue_story(uuid)
  File "/home/grant/Workspace/updog-news/app/queue.py", line 20, in queue_story
    generate.queue(uuid)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_rq2/functions.py", line 127, in queue
    return self.rq.get_queue(queue_name).enqueue_call(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 719, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 1094, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 1114, in _enqueue_job
    job.redis_server_version = self.get_redis_server_version()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/queue.py", line 208, in get_redis_server_version
    self.redis_server_version = get_version(self.connection)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/rq/utils.py", line 293, in get_version
    tuple(int(i) for i in str(connection.info("server")["redis_version"]).split('.')[:3]),
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/commands/core.py", line 996, in info
    return self.execute_command("INFO", section, *args, **kwargs)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 1074, in get_connection
    connection.connect()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/redis/connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
2025-01-11 13:25:10,179 - app - DEBUG - decide_respond:::Comment is a top level comment
2025-01-11 13:26:17,428 - app - DEBUG - decide_respond:::Comment is a top level comment
2025-01-11 13:48:58,034 - app - ERROR - Exception on /story/2e310d1c-12c0-4d64-97a2-20e6ac71f0b6/Joe biden runs again [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 124, in story
    results = Story.query.filter_by(uuid=uuid).first()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask_sqlalchemy/model.py", line 22, in __get__
    return cls.query_class(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 275, in __init__
    self._set_entities(entities)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 287, in _set_entities
    self._raw_columns = [
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 288, in <listcomp>
    coercions.expect(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 389, in expect
    insp._post_inspect
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2711, in _post_inspect
    self._check_configure()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2388, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 4204, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 4245, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 2405, in _post_configure_properties
    prop.init()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/interfaces.py", line 584, in init
    self.do_init()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 1647, in do_init
    self._generate_backref()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/relationships.py", line 2075, in _generate_backref
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Error creating backref 'user' on relationship 'User.liked_stories': property of that name exists on mapper 'Mapper[Story(story)]'
2025-01-11 15:56:30,254 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 374, in like
    current_user.liked_stories.add(story)
AttributeError: 'InstrumentedList' object has no attribute 'add'
2025-01-11 16:01:11,860 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: story.title

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 376, in like
    db.session.commit()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: story.title
[SQL: INSERT INTO story (uuid, title, content, guideline, trashed, archived, likes, user_id, reporter_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('12879ec0-d54e-44a6-a4f0-38b664e8a5b6', None, None, None, 0, 0, 0, 2, None)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-01-11 16:02:43,172 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: story.title

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 377, in like
    db.session.commit()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: story.title
[SQL: INSERT INTO story (uuid, title, content, guideline, trashed, archived, likes, user_id, reporter_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('12879ec0-d54e-44a6-a4f0-38b664e8a5b6', None, None, None, 0, 0, 0, 2, None)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-01-11 16:03:08,662 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 375, in like
    current_user.liked_stories.append(story)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/collections.py", line 1131, in append
    item = __set(self, item, _sa_initiator, NO_KEY)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/collections.py", line 1096, in __set
    item = executor.fire_append_event(item, _sa_initiator, key=key)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/collections.py", line 688, in fire_append_event
    return self.attr.fire_append_event(
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1752, in fire_append_event
    value = fn(state, value, initiator or self._append_token, key=key)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 63, in append
    item_state = attributes.instance_state(item)
AttributeError: 'Query' object has no attribute '_sa_instance_state'
2025-01-11 16:07:32,065 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 379, in like
    return jsonify({"status": status})
UnboundLocalError: local variable 'status' referenced before assignment
2025-01-11 16:22:49,211 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 371, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:23:26,803 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 371, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:24:03,657 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 371, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:24:05,123 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 371, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:24:57,540 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 372, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:31:31,117 - app - ERROR - Exception on /story/12879ec0-d54e-44a6-a4f0-38b664e8a5b6/Joe biden did what [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 149, in story
    return render_template("story.html", **story, form=form, forms=forms, top_level_comments=top_level_comments, comment_tree=comment_tree, logged_in=current_user.is_authenticated())
TypeError: 'bool' object is not callable
2025-01-11 16:34:28,175 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 372, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:34:32,110 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 372, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:34:33,761 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 372, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:43:48,398 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 371, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:45:57,272 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [GET]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 371, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:46:05,929 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 371, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-01-11 16:46:07,483 - app - ERROR - Exception on /like/12879ec0-d54e-44a6-a4f0-38b664e8a5b6 [POST]
Traceback (most recent call last):
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/grant/Workspace/updog-news/.venv/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/grant/Workspace/updog-news/app/routes/main.py", line 371, in like
    status = ("liked" if story in current_user.liked_stories else "unliked")
AttributeError: 'AnonymousUserMixin' object has no attribute 'liked_stories'
2025-03-26 02:37:57,789 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:37:57,789 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:37:57,824 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:37:57,824 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:37:57,824 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:37:57,824 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:37:59,042 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:37:59,042 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:37:59,075 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:37:59,075 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:37:59,076 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:37:59,076 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:38:14,123 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:38:14,123 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:38:14,154 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:38:14,154 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:38:14,154 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:38:14,154 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:38:34,727 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:38:34,727 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:38:34,758 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:38:34,758 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:38:34,759 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:38:34,759 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:38:35,911 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:38:35,911 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:38:35,940 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:38:35,940 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:38:35,941 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:38:35,941 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:39:04,430 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:39:04,430 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:39:04,462 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:39:04,462 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:39:04,463 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:39:04,463 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:40:03,167 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:40:03,167 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:40:03,198 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:40:03,198 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:40:03,198 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:40:03,198 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:40:12,010 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:40:12,010 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:40:12,040 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:40:12,040 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:40:12,040 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:40:12,040 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:40:22,776 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:40:22,776 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:40:22,808 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:40:22,808 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:40:22,809 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:40:22,809 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:40:24,301 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:40:24,301 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:40:24,334 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:40:24,334 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:40:24,334 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:40:24,334 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:40:43,485 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:40:43,485 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:40:43,517 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:40:43,517 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:40:43,518 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:40:43,518 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:42:04,164 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:42:04,164 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:42:04,195 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:42:04,195 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:42:04,196 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:42:04,196 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:42:05,458 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:42:05,458 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:42:05,491 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:42:05,491 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:42:05,492 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:42:05,492 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:43:00,309 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:43:00,309 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:43:00,344 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:43:00,344 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:43:00,345 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:43:00,345 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:43:01,061 - app.superintend.main - DEBUG - Hoodlem resp: Hello. How can I assist you today?
2025-03-26 02:43:01,061 - app.superintend.main - DEBUG - Hoodlem resp: Hello. How can I assist you today?
2025-03-26 02:43:21,691 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:43:21,691 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:43:21,720 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:43:21,720 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:43:21,721 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:43:21,721 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:43:22,256 - app.superintend.main - DEBUG - Hoodlem resp: I'm an artificial intelligence model known as Llama. Llama stands for "Large Language Model Meta AI."
2025-03-26 02:43:22,256 - app.superintend.main - DEBUG - Hoodlem resp: I'm an artificial intelligence model known as Llama. Llama stands for "Large Language Model Meta AI."
2025-03-26 02:45:30,057 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:45:30,057 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:45:30,088 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:45:30,088 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:45:30,089 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:45:30,089 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:45:31,082 - app.superintend.main - DEBUG - Hoodlem resp: I'm an artificial intelligence model known as Llama. Llama stands for "Large Language Model Meta AI."SCRIPTOR

I was developed at Meta with a combination of machine learning algorithms and large amounts of data, plus lots of human oversight from a large team of people. I'm constantly learning and improving, so over time I will likely become even more useful in my responses.

I can be used in a variety of ways, from helping you plan a vacation to creating art. I'm here to assist you in finding the help or information you need. My strengths include answering questions, generating text and images and even just chatting with you.
2025-03-26 02:45:31,082 - app.superintend.main - DEBUG - Hoodlem resp: I'm an artificial intelligence model known as Llama. Llama stands for "Large Language Model Meta AI."SCRIPTOR

I was developed at Meta with a combination of machine learning algorithms and large amounts of data, plus lots of human oversight from a large team of people. I'm constantly learning and improving, so over time I will likely become even more useful in my responses.

I can be used in a variety of ways, from helping you plan a vacation to creating art. I'm here to assist you in finding the help or information you need. My strengths include answering questions, generating text and images and even just chatting with you.
2025-03-26 02:46:07,145 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:46:07,145 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:46:07,176 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:46:07,176 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:46:07,177 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:46:07,177 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:46:09,070 - app.superintend.main - DEBUG - Hoodlem resp: Nice to meet you, Bob1. I am an artificial intelligence language model, so I don't have a personal life or experiences like humans do. However, I can tell you about my capabilities and what I can do to assist you.

I've been trained on a vast amount of text data, which allows me to generate human-like responses to a wide range of questions and topics. I can provide information, answer questions, and engage in conversations to the best of my knowledge based on my training data.

My strengths include:

1. **Knowledge base**: I have been trained on a massive amount of text data, which gives me access to a broad range of knowledge on various subjects, including history, science, technology, literature, and more.
2. **Language understanding**: I can comprehend and process natural language, allowing me to understand the context and nuances of human language.
3. **Response generation**: I can generate human-like responses to questions and prompts, using a combination of my knowledge base and language understanding capabilities.
4. **Conversation**: I can engage in conversations, using context and understanding to respond to follow-up questions and statements.

My limitations include:

1. **Lack of personal experiences**: As a machine, I don't have personal experiences, emotions, or opinions like humans do.
2. **Training data limitations**: My knowledge is limited to the data I've been trained on, and I may not always have the most up-to-date or accurate information on very recent events or developments.
3. **Contextual understanding**: While I can understand language, I may not always understand the context or subtleties of human communication, such as tone, sarcasm, or implied meaning.

I'm here to help answer your questions, provide information, and engage in conversations to the best of my abilities. What would you like to talk about, Bob1?
2025-03-26 02:46:09,070 - app.superintend.main - DEBUG - Hoodlem resp: Nice to meet you, Bob1. I am an artificial intelligence language model, so I don't have a personal life or experiences like humans do. However, I can tell you about my capabilities and what I can do to assist you.

I've been trained on a vast amount of text data, which allows me to generate human-like responses to a wide range of questions and topics. I can provide information, answer questions, and engage in conversations to the best of my knowledge based on my training data.

My strengths include:

1. **Knowledge base**: I have been trained on a massive amount of text data, which gives me access to a broad range of knowledge on various subjects, including history, science, technology, literature, and more.
2. **Language understanding**: I can comprehend and process natural language, allowing me to understand the context and nuances of human language.
3. **Response generation**: I can generate human-like responses to questions and prompts, using a combination of my knowledge base and language understanding capabilities.
4. **Conversation**: I can engage in conversations, using context and understanding to respond to follow-up questions and statements.

My limitations include:

1. **Lack of personal experiences**: As a machine, I don't have personal experiences, emotions, or opinions like humans do.
2. **Training data limitations**: My knowledge is limited to the data I've been trained on, and I may not always have the most up-to-date or accurate information on very recent events or developments.
3. **Contextual understanding**: While I can understand language, I may not always understand the context or subtleties of human communication, such as tone, sarcasm, or implied meaning.

I'm here to help answer your questions, provide information, and engage in conversations to the best of my abilities. What would you like to talk about, Bob1?
2025-03-26 02:46:27,844 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:46:27,844 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:46:27,873 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:46:27,873 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:46:27,874 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:46:27,874 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:46:28,409 - app.superintend.main - DEBUG - Hoodlem resp: Your name is Bob1.
2025-03-26 02:46:28,409 - app.superintend.main - DEBUG - Hoodlem resp: Your name is Bob1.
2025-03-26 02:46:29,049 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:46:29,049 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:46:29,078 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:46:29,078 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:46:29,078 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:46:29,078 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:46:29,549 - app.superintend.main - DEBUG - Hoodlem resp: Your name is Bob1.
2025-03-26 02:46:29,549 - app.superintend.main - DEBUG - Hoodlem resp: Your name is Bob1.
2025-03-26 02:46:39,008 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:46:39,008 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:46:39,037 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:46:39,037 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:46:39,038 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:46:39,038 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:46:39,584 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 02:46:39,584 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 02:49:21,582 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:49:21,582 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:49:21,614 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:49:21,614 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:49:21,614 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:49:21,614 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:49:22,195 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 02:49:22,195 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 02:53:31,384 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:53:31,384 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:53:31,412 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:53:31,412 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:53:31,413 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:53:31,413 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:53:31,953 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 02:53:31,953 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 02:55:22,271 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:55:22,271 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 02:55:22,304 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:55:22,304 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 02:55:22,304 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:55:22,304 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 02:55:22,849 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 02:55:22,849 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:03:56,253 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:03:56,253 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:03:56,283 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:03:56,283 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:03:56,283 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:03:56,283 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:17:55,944 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:17:55,944 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:17:55,976 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:17:55,976 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:17:55,976 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:17:55,976 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:17:56,587 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:17:56,587 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:18:37,480 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:18:37,480 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:18:37,509 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:18:37,509 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:18:37,509 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:18:37,509 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:18:38,057 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:18:38,057 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:19:10,603 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:19:10,603 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:19:10,632 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:19:10,632 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:19:10,633 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:19:10,633 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:19:11,118 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:19:11,118 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:19:12,511 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:19:12,511 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:19:12,540 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:19:12,540 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:19:12,541 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:19:12,541 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:19:13,010 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:19:13,010 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:23:28,753 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:23:28,753 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:23:28,790 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:23:28,790 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:23:28,790 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:23:28,790 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:23:51,380 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:23:51,380 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:23:51,411 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:23:51,411 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:23:51,411 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:23:51,411 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:24:43,486 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:24:43,486 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:24:43,520 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:24:43,520 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:24:43,520 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:24:43,520 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:24:44,033 - app.superintend.main - DEBUG - Hoodlem resp: Your name is Bob2.
2025-03-26 03:24:44,033 - app.superintend.main - DEBUG - Hoodlem resp: Your name is Bob2.
2025-03-26 03:24:45,272 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:24:45,272 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:24:45,301 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:24:45,301 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:24:45,302 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:24:45,302 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:24:45,775 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:24:45,775 - app.superintend.main - DEBUG - Hoodlem resp: Your name is bob2.
2025-03-26 03:26:07,385 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:26:07,385 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:26:07,415 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:26:07,415 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:26:07,416 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:26:07,416 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:26:09,230 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:26:09,230 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 03:26:09,260 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:26:09,260 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 03:26:09,261 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 03:26:09,261 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:10:46,676 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:10:46,676 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:10:46,717 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:10:46,717 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:10:46,717 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:10:46,717 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:11:30,151 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:11:30,151 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:11:30,198 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:11:30,198 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:11:30,198 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:11:30,198 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:11:32,340 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:11:32,340 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:11:32,393 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:11:32,393 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:11:32,393 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:11:32,393 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:12:32,501 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:12:32,501 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:12:32,560 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:12:32,560 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:12:32,560 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:12:32,560 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:15:01,141 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:15:01,141 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:15:01,198 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:15:01,198 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:15:01,198 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:15:01,198 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:15:03,426 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:15:03,426 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:15:03,476 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:15:03,476 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:15:03,477 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:15:03,477 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:15:30,071 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:15:30,071 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:15:30,125 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:15:30,125 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:15:30,126 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:15:30,126 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:22:46,804 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:22:46,804 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:22:46,851 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:22:46,851 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:22:46,851 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:22:46,851 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:41:05,207 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:41:05,207 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:41:05,254 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:41:05,254 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:41:05,255 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:41:05,255 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:42:11,628 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:42:11,628 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:42:11,673 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:42:11,673 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:42:11,673 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:42:11,673 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:42:22,329 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:42:22,329 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:42:22,376 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:42:22,376 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:42:22,376 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:42:22,376 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:42:49,344 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:42:49,344 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:42:49,388 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:42:49,388 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:42:49,389 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:42:49,389 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:42:51,864 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:42:51,864 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:42:51,914 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:42:51,914 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:42:51,915 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:42:51,915 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:43:32,807 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:43:32,807 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 15:43:32,853 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:43:32,853 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 15:43:32,853 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 15:43:32,853 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:14:20,440 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:14:20,440 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:14:20,490 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:14:20,490 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:14:20,491 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:14:20,491 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:15:11,984 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:15:11,984 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:15:12,030 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:15:12,030 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:15:12,031 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:15:12,031 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:15:27,473 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:15:27,473 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:15:27,521 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:15:27,521 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:15:27,522 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:15:27,522 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:15:41,255 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:15:41,255 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:15:41,304 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:15:41,304 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:15:41,305 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:15:41,305 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:16:37,605 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:16:37,605 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:16:37,653 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:16:37,653 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:16:37,653 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:16:37,653 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:17:33,914 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:17:33,914 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:17:33,998 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:17:33,998 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:17:33,998 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:17:33,998 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:17:53,601 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:17:53,601 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:17:53,703 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:17:53,703 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:17:53,704 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:17:53,704 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:18:20,630 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:18:20,630 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:18:20,728 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:18:20,728 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:18:20,729 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:18:20,729 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:19:44,473 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:19:44,473 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:19:44,525 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:19:44,525 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:19:44,526 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:19:44,526 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:19:46,962 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:19:46,962 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:19:47,020 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:19:47,020 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:19:47,020 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:19:47,020 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:22:12,177 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:22:12,177 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:22:12,272 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:22:12,272 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:22:12,273 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:22:12,273 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:22:35,897 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:22:35,897 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:22:35,947 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:22:35,947 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:22:35,947 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:22:35,947 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:22:36,973 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:22:36,973 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:22:36,973 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:22:37,087 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:22:37,087 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:22:37,087 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:22:37,088 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:22:37,088 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:22:37,088 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:23:15,017 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:23:15,017 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:23:15,067 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:23:15,067 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:23:15,068 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:23:15,068 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:23:32,010 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:23:32,010 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:23:32,109 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:23:32,109 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:23:32,113 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:23:32,113 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:53:45,103 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:53:45,103 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:53:45,151 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:53:45,151 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:53:45,152 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:53:45,152 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:54:19,310 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:54:19,310 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:54:19,399 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:54:19,399 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:54:19,400 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:54:19,400 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:54:21,750 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:54:21,750 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:54:21,853 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:54:21,853 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:54:21,854 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:54:21,854 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:59:55,632 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:59:55,632 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:59:55,692 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:59:55,692 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:59:55,693 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:59:55,693 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:59:57,339 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:59:57,339 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 16:59:57,384 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:59:57,384 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 16:59:57,385 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 16:59:57,385 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 17:00:25,751 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 17:00:25,751 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 17:00:25,794 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 17:00:25,794 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 17:00:25,795 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 17:00:25,795 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 17:00:44,991 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 17:00:44,991 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 17:00:45,033 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 17:00:45,033 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 17:00:45,033 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 17:00:45,033 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 17:08:39,428 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 17:08:39,428 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 17:08:39,489 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 17:08:39,489 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 17:08:39,490 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 17:08:39,490 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 17:08:41,364 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 17:08:41,364 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 17:08:41,412 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 17:08:41,412 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 17:08:41,413 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 17:08:41,413 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 18:38:06,181 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 18:38:06,181 - app.superintend.main - DEBUG - Creating Groq and Featherless clients
2025-03-26 18:38:06,273 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 18:38:06,273 - app.superintend.main - DEBUG - Initializing chat queue
2025-03-26 18:38:06,274 - app.superintend.main - DEBUG - Created Superintendent
2025-03-26 18:38:06,274 - app.superintend.main - DEBUG - Created Superintendent
